# Generated by Django 4.0.4 on 2022-04-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_post_image_alter_post_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyVideo',
            new_name='MyWork',
        ),
    ]
