# Generated by Django 4.0.4 on 2022-04-21 02:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_myvideo_mywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(unique=True, upload_to='biography')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mywork',
            name='main_image',
            field=models.ImageField(unique=True, upload_to='works/images'),
        ),
        migrations.AlterField(
            model_name='mywork',
            name='video',
            field=models.FileField(unique=True, upload_to='works/video'),
        ),
    ]
